#!/usr/bin/env ruby


require_relative 'models/story'


def menu
<<EOS

--------Menu-----------------------------------

How would you like to search for short stories?

1. See a list of all stories
2. Search by Genre
3. Search by Author
4. Search by Year
5. Add your own stupid story
6. Update your sob story
7. Delete your bad story

-----------------------------------------------
EOS
end

def get_menu_selection
  puts menu
  input = gets
  return unless input
  input = input.chomp
  if input == "1"
    puts "\nWhat story would you like to read?\n\n"
    Story.print_all
    input = gets
    input = input.chomp
    puts "--------"
    Story.find_story_by_id(input)
    puts "\n\nWould you like to search for another story? (y/n)\n\n"
    input = gets
    input = input.chomp
    if input == "y"
      get_menu_selection
    end
  
  elsif input == "2"
    puts "\n\nWhat is the genre you would like to search?\n\n"
    Story.print_genres
    input = gets
    input = input.chomp
    puts "--------"
    puts "What story would you like to read?\n\n"
    Story.find_stories_with_search(input, "genre")
    input = gets
    input = input.chomp
    puts "--------"
    Story.find_story(input)
    puts "\n\nWould you like to search for another story? (y/n)\n\n"
    input = gets
    input = input.chomp
    if input == "y"
      get_menu_selection
    end
  
  elsif input == "3"
    puts "\n\nWhat is the name of the author you would like to search?\n\n"
    Story.print_authors
    input = gets
    input = input.chomp
    puts "--------"
    puts "What story would you like to read?\n\n"
    Story.find_stories_with_search(input, "author")
    input = gets
    input = input.chomp
    puts "--------"
    Story.find_story(input)
    puts "\n\nWould you like to search for another story? (y/n)\n\n"
    input = gets
    input = input.chomp
    if input == "y"
      get_menu_selection
    end
  
  elsif input == "4"
    puts "\n\nWhat is the year you would like to search?\n\n"
    Story.print_years
    input = gets.chomp
    puts "--------"
    puts "What story would you like to read?\n\n"
    Story.find_stories_with_search(input, "year")
    input = gets
    input = input.chomp
    puts "--------"
    Story.find_story(input)
    puts "\n\nWould you like to search for another story? (y/n)\n\n"
    input = gets
    input = input.chomp
    if input == "y"
      get_menu_selection
    end

  elsif input == "5"
    puts "\n\nWhat is the title of the story you would like to add?\n\n"
    title = gets.chomp
    puts "--------"
    puts "\n\nWhat is the genre of the story you would like to add?\n\n"
    genre = gets.chomp
    puts "--------"
    puts "\n\nWho is the author of the story?\n\n"
    puts "--------"
    author = gets.chomp
    puts "\n\nWhat year was it written?\n\n"
    puts "--------"
    year = gets.chomp
    puts "\n\nWhat's your story?\n\n"
    puts "--------"
    story = gets.chomp
    story = Story.new(title, genre, author, year, story)
    story.save
    get_menu_selection

  elsif input == "6"
    Story.print_all
    puts "\n\nSelect the number of the story you would like to edit.\n\n"
    id = gets.chomp
    puts "--------"
    puts "\n\nWhat is the title of the story you would like to update?\n\n"
    title = gets.chomp
    puts "--------"
    puts "\n\nWhat is the genre of the story you would like to update?\n\n"
    genre = gets.chomp
    puts "--------"
    puts "\n\nWho is the author of the story?\n\n"
    puts "--------"
    author = gets.chomp
    puts "\n\nWhat year was it written?\n\n"
    puts "--------"
    year = gets.chomp
    puts "\n\nWhat's your story?\n\n"
    puts "--------"
    story = gets.chomp
    updated_story = Story.new(title, genre, author, year, story)
    updated_story.update(id)
    get_menu_selection

  elsif input == "7"
    Story.print_all
    puts "\n\nSelect the number of the story you would like to delete.\n\n"
    input = gets.chomp
    puts "--------"
    Story.delete(input)
    get_menu_selection

  else
    puts "'#{input}' is an invalid option. Try again."
    get_menu_selection
  end

end

get_menu_selection
